'use strict';

exports.BattleItems = {
    "playniumz": {
        spritenum: 656,
		onTakeItem: false,
		id: "playniumz",
		name: "Playnium Z",
		zMove: "Exiled From All Others",
		zMoveFrom: "Aqua Subscribe",
		zMoveUser: ["Ludicolo"],
		num: -1,
		gen: -1,
		desc: "If holder is a Ludicolo with Aqua Subscribe, it can use Exiled From All Others.",
    },
    "flarez": {
        spritenum: 656,
        onTakeItem: false,
        zMove: "Teraflare",
        zMoveFrom: "Megaflare",
        name: "Flare Z",
        id: "flarez",
        zMoveUser: ["Groudon-Primal"],
        num: -2,
        gen: -1,
        desc: "If holder is a Groudon-Primal with Megaflare, it can use Teraflare.",
    },
    "thekidz": {
        spritenum: 656,
        onTakeItem: false,
        zMove: "Accept The Memes",
        zMoveFrom: "Attitude Adjustment",
        name: "thekidz",
        id: "thekidz",
        zMoveUser: ["Mewtwo"],
        num: -3,
        gen: -1,
        desc: "If holder is Mewtwo with Attitude Adjustment, it can use Accept The Memes.",
    },
};